// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! cidata builds FAT12 file systems for use with [cloud-init]'s [`NoCloud`]
//! data provider.
//!
//! [cloud-init]: https://cloudinit.readthedocs.io/en/latest/index.html
//! [`NoCloud`]: https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html
//!
//! File systems generated by this crate are built to the exact size of the
//! input files and are not intended for read-write use. This crate differs from
//! a complete FAT file system generator in that the file names are hard-coded,
//! directories other than the root directory are not supported, file timestamps
//! are not written, and only 12-bit FATs are supported owing to the small data
//! size expected in the volume.
//!
//! This crate is capable of generating file systems containing up to
//! approximately 127 MiB of data, but users should keep in mind that FAT12
//! was designed for floppy disks and should generally not be used for volumes
//! larger than 4 MiB.

// Quotes in comments are from the _Microsoft Extensible Firmware Initiative
// FAT32 File System Specification_, dated December 6, 2000, with some minor
// edits for readability. It's a recommended read if you like specifications
// where the author has clearly seen some shit.

use std::fmt::Debug;
use std::fmt::Display;
use std::num::NonZero;

use bytemuck::AnyBitPattern;
use bytemuck::NoUninit;
use bytemuck::Pod;
use bytemuck::Zeroable;

const FILES: usize = 4;
const BYTES_PER_SECTOR: u16 = 512;
/// "Number of sectors per allocation unit. This value must be a power of 2
/// that is greater than 0.... Values that cause a cluster size greater than 32K
/// bytes do not work properly; do not try to define one." Using a `NonZero<u8>`
/// allows the compiler to optimize out some panics.
const VALID_SECTORS_PER_CLUSTER: [NonZero<u8>; 7] = [
    NonZero::new(1).unwrap(),
    NonZero::new(2).unwrap(),
    NonZero::new(4).unwrap(),
    NonZero::new(8).unwrap(),
    NonZero::new(16).unwrap(),
    NonZero::new(32).unwrap(),
    NonZero::new(64).unwrap(),
];
/// "There is no such thing as a FAT12 volume that has more than 4084
/// clusters.... the world is full of FAT code that is wrong. There is a lot of
/// FAT type code that is off by 1 or 2 or 8 or 10 or 16. For this reason, it is
/// highly recommended that if you are formatting a FAT volume which has maximum
/// compatibility with all existing FAT code ... Stay at least 16 clusters on
/// each side away from these cut-over cluster counts."
const MAX_CLUSTERS: u16 = 4084 - 16;
/// macOS diskarbitrationd (tested on 13.7.6) refuses to mount any disk it
/// cannot fsck, and fsck fails on FAT disks smaller than 4 KiB because it tries
/// to read an entire 4 KiB page into memory, since the initial sector _could_
/// be that large. This seems like a reasonable "no image should ever be smaller
/// than this" size.
const MIN_SECTORS: u32 = 4096 / BYTES_PER_SECTOR as u32;
/// The number of reserved entries at the start of the FAT.
const RESERVED_FAT_ENTRIES: u16 = 2;
/// "The count of FAT data structures on the volume. This field should always
/// contain the value 2 for any FAT volume of any type."
const FAT_COUNT: u8 = 2;
/// "0xF8 is the standard value for 'fixed' (non-removable) media."
const MEDIA_TYPE: u8 = 0xF8;
/// The required volume label is specified by cloud-init. It must be lowercase,
/// a minor technical violation of FAT.
const VOLUME_LABEL: ShortName = ShortName(*b"cidata     ");

#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[must_use]
pub struct Cidata<'a> {
    pub meta_data: Option<&'a [u8]>,
    pub network_config: Option<&'a [u8]>,
    pub user_data: Option<&'a [u8]>,
    pub vendor_data: Option<&'a [u8]>,
}

impl Cidata<'_> {
    /// Create a new `Cidata` with no files.
    pub const fn new() -> Self {
        Self {
            meta_data: None,
            network_config: None,
            user_data: None,
            vendor_data: None,
        }
    }

    /// Generate a FAT12 file system containing these files.
    ///
    /// # Errors
    ///
    /// Returns an error if the data is too large for a FAT12 file system.
    pub fn generate(&self) -> Result<Vec<u8>, Error> {
        let data = [
            self.meta_data,
            self.network_config,
            self.user_data,
            self.vendor_data,
        ];
        let mut file_layout = [const { FileLayout::NotPresent }; FILES];
        let mut cluster_chain_ends = [const { None }; FILES];
        // The first valid sectors-per-cluster value we find won't necessarily
        // produce the smallest volume, because halving the size of the FAT can
        // save more sectors than the overhead of a larger cluster size. But in
        // the expected average case the FAT will never exceed a single sector,
        // so we will not concern ourselves with that.
        let (data_clusters, sectors_per_cluster) = VALID_SECTORS_PER_CLUSTER
            .iter()
            .copied()
            .find_map(|sectors_per_cluster| {
                let bytes_per_cluster = u32::from(BYTES_PER_SECTOR)
                    * u32::from(sectors_per_cluster.get());
                let mut fat_entries = RESERVED_FAT_ENTRIES;
                for ((layout, end), data) in file_layout
                    .iter_mut()
                    .zip(&mut cluster_chain_ends)
                    .zip(&data)
                {
                    let Some(data) = data else { continue };
                    let len = data.len().try_into().ok()?;
                    let start = if data.is_empty() { 0 } else { fat_entries };
                    *layout = FileLayout::Present { start, len };
                    fat_entries = fat_entries.checked_add(
                        len.div_ceil(bytes_per_cluster).try_into().ok()?,
                    )?;
                    *end = Some(NonZero::new(fat_entries - 1)?);
                }
                let data_clusters = fat_entries - RESERVED_FAT_ENTRIES;
                (data_clusters <= MAX_CLUSTERS)
                    .then_some((data_clusters, sectors_per_cluster))
            })
            .ok_or(Error::StorageFull)?;

        let fat_bits = (data_clusters + RESERVED_FAT_ENTRIES) * 12;
        let fat_sectors = fat_bits.div_ceil(8 * BYTES_PER_SECTOR);

        let boot_sector = 1;
        // A directory entry is 32 bytes, and we have a maximum of 10 entries
        // (volume label, each file is 2 entries except `network-config` which
        // is 3), so the root directory always fits in a single sector.
        let root_directory_sector = 1;
        let total_sectors = boot_sector
            + u32::from(fat_sectors) * u32::from(FAT_COUNT)
            + root_directory_sector
            + u32::from(data_clusters) * u32::from(sectors_per_cluster.get());
        let total_sectors = total_sectors.max(MIN_SECTORS);

        let volume_size = usize::from(BYTES_PER_SECTOR)
            * usize::try_from(total_sectors).map_err(|_| Error::StorageFull)?;
        let mut volume = Vec::with_capacity(volume_size);

        volume.extend_from_slice(bytemuck::bytes_of(&BootSector::new(
            sectors_per_cluster.get(),
            total_sectors,
            fat_sectors,
        )));
        write_fats(&mut volume, fat_sectors, fat_bits, cluster_chain_ends);
        write_root_directory(&mut volume, &file_layout);

        let bytes_per_cluster = usize::from(sectors_per_cluster.get())
            * usize::from(BYTES_PER_SECTOR);
        for data in data.iter().flatten() {
            volume.extend_from_slice(data);
            let remainder = data.len() % bytes_per_cluster;
            if remainder > 0 {
                volume.resize(volume.len() + bytes_per_cluster - remainder, 0);
            }
        }

        debug_assert!(volume.len() <= volume_size);
        if volume.len() < volume_size {
            volume.resize(volume_size, 0);
        }

        Ok(volume)
    }
}

#[derive(Debug)]
#[non_exhaustive]
pub enum Error {
    /// The provided data is too large for a FAT12 file system.
    StorageFull,
}

impl Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::StorageFull => {
                write!(f, "data too large for FAT12 file system")
            }
        }
    }
}

impl std::error::Error for Error {}

#[derive(Debug, Clone, Copy, AnyBitPattern, NoUninit)]
#[repr(C)]
struct BootSector {
    jmp_boot: [u8; 3],
    oem_name: [u8; 8],
    bytes_per_sector: U16,
    sectors_per_cluster: u8,
    reserved_sector_count: U16,
    fat_count: u8,
    root_entry_count: U16,
    total_sectors_u16: U16,
    media: u8,
    fat_size: U16,
    sectors_per_track: U16,
    heads: U16,
    hidden_sectors: U32,
    total_sectors_u32: U32,
    drive_number: u8,
    reserved: u8,
    boot_signature: u8,
    volume_id: U32,
    volume_label: ShortName,
    file_system_type: [u8; 8],
    boot_code: [u8; 448],
    signature: [u8; 2],
}

impl BootSector {
    fn new(
        sectors_per_cluster: u8,
        total_sectors: u32,
        fat_sectors: u16,
    ) -> Self {
        Self {
            // The spec suggests using "MSWIN4.1" here because some FAT drivers
            // care about the value of this field. Until we find a platform that
            // rejects it, we'll prefer to use an OEM name that blames us for
            // any mistakes.
            oem_name: *b"cidatars",
            bytes_per_sector: U16::new(BYTES_PER_SECTOR),
            sectors_per_cluster,
            // "For FAT12 and FAT16 volumes, this value should never be anything
            // other than 1."
            reserved_sector_count: U16::new(1),
            // "The count of FAT data structures on the volume. This field
            // should always contain the value 2 for any FAT volume of any
            // type."
            fat_count: 2,
            // "For FAT12 and FAT16 volumes, this value should always specify
            // a count that when multipled by 32 results in an even multiple of
            // [`bytes_per_sector`]." All of the directory entries we can have
            // fit into 512 bytes, so this will always be 1 sector.
            root_entry_count: U16::new(BYTES_PER_SECTOR / 32),
            total_sectors_u16: U16::new(total_sectors.try_into().unwrap_or(0)),
            media: MEDIA_TYPE,
            // "This field is the FAT12/FAT16 16-bit count of sectors occupied
            // by ONE FAT."
            fat_size: U16::new(fat_sectors),
            // "This field is only relevant for media that have a geometry ...
            // and are visible on interrupt 0x13." cidata volumes are generally
            // virtual hardware and thus do not have "tracks" or "heads"
            // but we'll go ahead and use the numbers from a double-sided
            // high-density 3.5-inch floppy disk.
            sectors_per_track: U16::new(18),
            heads: U16::new(2),
            // "This field should always be zero on media that are not
            // partitioned."
            hidden_sectors: U32::new(0),
            total_sectors_u32: if u16::try_from(total_sectors).is_ok() {
                U32::new(0)
            } else {
                U32::new(total_sectors)
            },
            // "INT 13h drive number. This field supports MS-DOS bootstrap."
            // There is not really a way to know this ahead of time, so set it
            // to the same thing every other tool does.
            drive_number: 0x80,
            // "Code that formats FAT volumes should always set this byte to 0."
            reserved: 0,
            // "Extended boot signature (0x29). This is a signature byte that
            // indicates that the following three fields in the boot sector
            // are present."
            boot_signature: 0x29,
            volume_id: U32::new(0x1de_c1da),
            volume_label: VOLUME_LABEL,
            // File system type. "Many people think that the string in this
            // field has something to do with the determination of what type of
            // FAT that the volume has. This is not true.... This string should
            // be set based on the FAT type though, because some FAT file system
            // drivers do look at it."
            file_system_type: *b"FAT12   ",

            ..*bytemuck::from_bytes(include_bytes!("boot"))
        }
    }
}

fn write_fats(
    volume: &mut Vec<u8>,
    fat_sectors: u16,
    fat_bits: u16,
    cluster_chain_ends: [Option<NonZero<u16>>; FILES],
) {
    /// EOC mark ("End Of Clusterchain").
    const EOC: u16 = 0xfff;
    // Because we allocate clusters in order, each entry `n` therefore
    // contains `n + 1`, with the exception of the reserved clusters and the
    // last cluster of each file. This means we can statically define a FAT
    // for the largest possible image and fill in the EOC mark as needed at
    // runtime. This is at most ~6 KiB.
    const MAX_FAT_LEN: usize = ((MAX_CLUSTERS as usize + 2) * 12).div_ceil(8);
    static FAT: [u8; MAX_FAT_LEN] = {
        let mut fat = [0; MAX_FAT_LEN];
        // "The first reserved cluster, FAT[0], contains the `MEDIA_TYPE`
        // byte value in its low 8 bits, and all other bits are set to 1."
        write_fat_entry(&mut fat, 0, 0xf00 | MEDIA_TYPE as u16);
        // "The second reserved cluster, FAT[1] ... On FAT12 volumes, it is
        // not used and simply always contains an EOC mark."
        write_fat_entry(&mut fat, 1, EOC);
        let mut i = 2;
        while i < MAX_CLUSTERS + 2 {
            write_fat_entry(&mut fat, i as usize, i + 1);
            i += 1;
        }
        fat
    };

    let final_len =
        usize::from(fat_sectors + 1) * usize::from(BYTES_PER_SECTOR);
    // If fat_entries is odd, this doesn't copy the last half-byte of the FAT.
    // This doesn't matter though because if fat_entries is odd then there is
    // necessarily at least one file in the file system, and the last entry in
    // the FAT will be set to the EOC mark below.
    let copy_len = usize::from(fat_bits) / 8;
    volume.extend_from_slice(&FAT[..copy_len]);
    volume.resize(final_len, 0);

    // Fill in the EOC marks.
    let fat = &mut volume[BYTES_PER_SECTOR.into()..];
    for end in &cluster_chain_ends {
        let Some(end) = end else { continue };
        write_fat_entry(fat, end.get().into(), EOC);
    }

    // Copy the first FAT to the second FAT.
    volume.extend_from_within(usize::from(BYTES_PER_SECTOR)..);
}

const fn write_fat_entry(fat: &mut [u8], idx: usize, value: u16) {
    let offset = idx + idx / 2;
    // elides all of the index bounds checks
    assert!(offset + 1 < fat.len());

    if idx.is_multiple_of(2) {
        let [a, b] = value.to_le_bytes();
        fat[offset] = a;
        fat[offset + 1] &= 0xf0;
        fat[offset + 1] |= b & 0xf;
    } else {
        let [a, b] = (value << 4).to_le_bytes();
        fat[offset] &= 0xf;
        fat[offset] |= a;
        fat[offset + 1] = b;
    }
}

#[derive(Debug)]
enum FileLayout {
    NotPresent,
    Present { start: u16, len: u32 },
}

fn write_root_directory(volume: &mut Vec<u8>, files: &[FileLayout; FILES]) {
    volume.resize(volume.len() + usize::from(BYTES_PER_SECTOR), 0);
    let mut chunks = volume
        .last_chunk_mut::<{ BYTES_PER_SECTOR as usize }>()
        .unwrap()
        .chunks_exact_mut(32);
    chunks.next().unwrap().copy_from_slice(bytemuck::bytes_of(
        &DirEntry::volume_label(VOLUME_LABEL),
    ));

    macro_rules! entries {
        ($layout:expr, $short:expr, $long:expr) => {
            entries!($layout, $short => {
                chunks.next().unwrap().copy_from_slice(bytemuck::bytes_of(
                    &const { LongEntry::single(SHORT, $long)},
                ));
            })
        };
        ($layout:expr, $short:expr => $long_write:stmt) => {
            if let FileLayout::Present { start, len } = $layout {
                const SHORT: ShortName = ShortName(*$short);
                $long_write
                chunks.next().unwrap().copy_from_slice(bytemuck::bytes_of(
                    &DirEntry::new(SHORT, start, len),
                ));
            }
        };
    }
    entries!(files[0], b"META-D~1   ", "meta-data");
    entries!(files[1], b"NETWOR~1   " => {
        let longs = const { LongEntry::double(SHORT, "network-config") };
        chunks.next().unwrap().copy_from_slice(bytemuck::bytes_of(&longs[0]));
        chunks.next().unwrap().copy_from_slice(bytemuck::bytes_of(&longs[1]));
    });
    entries!(files[2], b"USER-D~1   ", "user-data");
    entries!(files[3], b"VENDOR~1   ", "vendor-data");
}

#[derive(Clone, Copy, AnyBitPattern, NoUninit)]
#[repr(C)]
struct ShortName([u8; 11]);

impl ShortName {
    const fn checksum(&self) -> u8 {
        let mut checksum = 0u8;
        let mut i = 0;
        while i < self.0.len() {
            checksum = checksum.rotate_right(1).wrapping_add(self.0[i]);
            i += 1;
        }
        checksum
    }
}

impl Debug for ShortName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", String::from_utf8_lossy(&self.0))
    }
}

#[derive(Debug, Clone, Copy, NoUninit)]
#[repr(u8)]
enum FileAttributes {
    Empty = 0,
    VolumeId = 8,
    LongName = 8 | 4 | 2 | 1,
}

#[derive(Debug, Clone, Copy, NoUninit)]
#[repr(C)]
struct DirEntry {
    name: ShortName,
    attr: FileAttributes,
    winnt_reserved: u8,
    creation_time_tenths: u8,
    creation_time: U16,
    creation_date: U16,
    access_date: U16,
    cluster_hi: U16,
    write_time: U16,
    write_date: U16,
    cluster_lo: U16,
    file_size: U32,
}

impl DirEntry {
    const fn new(name: ShortName, cluster: u16, file_size: u32) -> Self {
        Self {
            name,
            attr: FileAttributes::Empty,
            // "Reserved for use by Windows NT. Set value to 0 when a file is
            // created and never modify or look at it after that."
            winnt_reserved: 0,
            creation_time_tenths: 0,
            creation_time: U16::new(0),
            creation_date: U16::new(0),
            access_date: U16::new(0),
            // "High word of this entry's first cluster number (always 0 for a
            // FAT12 or FAT16 volume)."
            cluster_hi: U16::new(0),
            write_time: U16::new(0),
            write_date: U16::new(0),
            cluster_lo: U16(cluster.to_le_bytes()),
            file_size: U32(file_size.to_le_bytes()),
        }
    }

    const fn volume_label(name: ShortName) -> Self {
        Self { attr: FileAttributes::VolumeId, ..Self::new(name, 0, 0) }
    }
}

#[derive(Debug, Clone, Copy, NoUninit)]
#[repr(C)]
struct LongEntry {
    ord: u8,
    name1: [U16; 5],
    attr: FileAttributes,
    r#type: u8,
    checksum: u8,
    name2: [U16; 6],
    cluster_lo: U16,
    name3: [U16; 2],
}

impl LongEntry {
    const LAST_LONG_ENTRY: u8 = 0x40;

    #[expect(clippy::many_single_char_names)]
    const fn single(short_name: ShortName, long_name: &str) -> Self {
        assert!(long_name.is_ascii() && long_name.len() <= 13);
        let long_name = long_name.as_bytes();
        // Unused bytes are marked with 0xffff.
        let mut u16_name = [U16::new(0xffff); 13];
        let mut i = 0;
        while i < long_name.len() && i < u16_name.len() {
            u16_name[i] = U16::new(long_name[i] as u16);
            i += 1;
        }
        // Null-terminate the string, if there's room.
        if i < u16_name.len() {
            u16_name[i] = U16::new(0);
        }
        // We don't have `const fn` slice operators yet, but this works!
        let [a, b, c, d, e, f, g, h, i, j, k, l, m] = u16_name;

        Self {
            ord: 1 | Self::LAST_LONG_ENTRY,
            name1: [a, b, c, d, e],
            attr: FileAttributes::LongName,
            // "If zero, indicates a directory entry that is a sub-component of
            // a long name. NOTE: Other values reserved for future extensions."
            r#type: 0,
            checksum: short_name.checksum(),
            name2: [f, g, h, i, j, k],
            // "Must be ZERO. This is an artifact of the FAT "first cluster" and
            // must be zero for compatibility with existing disk utilities."
            cluster_lo: U16::new(0),
            name3: [l, m],
        }
    }

    const fn double(short_name: ShortName, long_name: &str) -> [Self; 2] {
        assert!(long_name.is_ascii());
        let (first, last) = long_name.split_at(13);
        [
            Self {
                ord: 2 | Self::LAST_LONG_ENTRY,
                ..Self::single(short_name, last)
            },
            Self { ord: 1, ..Self::single(short_name, first) },
        ]
    }
}

#[derive(Clone, Copy, Pod, Zeroable)]
#[repr(transparent)]
struct U16([u8; 2]);

impl U16 {
    const fn new(value: u16) -> Self {
        Self(value.to_le_bytes())
    }
}

impl Debug for U16 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", u16::from_le_bytes(self.0))
    }
}

#[derive(Clone, Copy, Pod, Zeroable)]
#[repr(transparent)]
struct U32([u8; 4]);

impl U32 {
    const fn new(value: u32) -> Self {
        Self(value.to_le_bytes())
    }
}

impl Debug for U32 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", u32::from_le_bytes(self.0))
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_write_fat_entry() {
        let mut v = [0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc];
        crate::write_fat_entry(&mut v, 0, 0xfed);
        assert_eq!(v, [0xed, 0x3f, 0x56, 0x78, 0x9a, 0xbc]);
        //               ^^     ^
        crate::write_fat_entry(&mut v, 1, 0xcba);
        assert_eq!(v, [0xed, 0xaf, 0xcb, 0x78, 0x9a, 0xbc]);
        //                     ^     ^^
        crate::write_fat_entry(&mut v, 2, 0x654);
        assert_eq!(v, [0xed, 0xaf, 0xcb, 0x54, 0x96, 0xbc]);
        //                                 ^^     ^
        crate::write_fat_entry(&mut v, 3, 0x321);
        assert_eq!(v, [0xed, 0xaf, 0xcb, 0x54, 0x16, 0x32]);
        //                                       ^     ^^
    }
}
