name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
        with:
          # use the HEAD, not the synthetic merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9
      - run: cargo nextest run --run-ignored all --no-capture
